version: '3'
services:
  # Selenium Grid Hub
  selenium-hub:
    image: selenium/hub
    ports:
      - '4444:4444'
    restart: always

  # Selenium grid chrome node
  selenium-node-chrome-1:
    image: selenium/node-chrome
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    restart: always

  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20231004
    volumes:
      - ./videos:/videos
    depends_on:
      - selenium-node-chrome-1
    environment:
      - DISPLAY_CONTAINER_NAME=selenium-node-chrome-1
      - FILE_NAME=chrome_video.mp4

  # Selenium grid firefox node
  selenium-node-firefox-1:
    image: selenium/node-firefox
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    restart: always

  firefox_video:
    image: selenium/video:ffmpeg-4.3.1-20231004
    volumes:
      - ./videos:/videos
    depends_on:
      - selenium-node-firefox-1
    environment:
      - DISPLAY_CONTAINER_NAME=selenium-node-firefox-1
      - FILE_NAME=firefox_video.mp4

  # Selenium grid edge node
  selenium-node-edge-1:
    image: selenium/node-edge
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    restart: always

  edge_video:
    image: selenium/video:ffmpeg-4.3.1-20231004
    volumes:
      - ./videos:/videos
    depends_on:
      - selenium-node-edge-1
    environment:
      - DISPLAY_CONTAINER_NAME=selenium-node-edge-1
      - FILE_NAME=edge_video.mp4