version: '3'
services:
  # Selenium chrome
  selenium-chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - '4444:4444'
      - "5901:5900"
      - '7901:7900'
    restart: always

  # Selenium firefox
  selenium-firefox:
    image: selenium/standalone-firefox-debug
    ports:
      - '4445:4444'
      - "5902:5900"
      - '7902:7900'
    restart: always