name: Destroy AWS Environment

on:
  workflow_dispatch:

jobs:
  test:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    runs-on: ubuntu-latest # runner

    steps:
      - uses: actions/checkout@v2
      - name: Initialize terraform
        run: sh ./scripts/terraform/init.sh
      - name: Destroy AWS infrastructure
        run: sh ./scripts/terraform/test-env/destroy.sh
