name: SuiteCRM Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_suitecrm:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    runs-on: ubuntu-latest # runner
    timeout-minutes: 15

    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v2
      - name: Create docker environment
        run: docker compose up -d
      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash
      - name: Show docker environment
        run: docker ps
      - name: Ping application
        run: curl http://localhost:80
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '19'
      - name: Run tests
        run: mvn clean test -Ddriver.name=chrome-remote -Ddriver.remoteUrl=http://localhost:4444/wd/hub