name: SuiteCRM Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_suitecrm:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    runs-on: ubuntu-latest # runner
    timeout-minutes: 15

    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
      mariadb:
        image: docker.io/bitnami/mariadb:10.3-debian-10
        ports:
          - 3306:3306
        env:
          ALLOW_EMPTY_PASSWORD: yes
          MARIADB_USER: bn_suitecrm
          MARIADB_DATABASE: bitnami_suitecrm
          MARIADB_ROOT_PASSWORD: root
          MARIADB_PASSWORD: root
      suitecrm:
        image: docker.io/bitnami/suitecrm:7-debian-10
        ports:
          - 8080:8080
        env:
          SUITECRM_DATABASE_HOST: mariadb
          SUITECRM_DATABASE_PORT_NUMBER: 3306
          SUITECRM_DATABASE_USER: bn_suitecrm
          SUITECRM_DATABASE_NAME: bitnami_suitecrm
          SUITECRM_DATABASE_PASSWORD: root
          ALLOW_EMPTY_PASSWORD: yes

    steps:
      - uses: actions/checkout@v4
      - name: Sleep for 45 seconds
        run: sleep 45s
        shell: bash
      - name: Ping application
        run: curl http://localhost:8080
      - name: Ping application
        run: wget http://localhost:8080
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '19'
      - name: Run tests
        run: mvn clean test -Ddriver.name=chrome-remote -Ddriver.remoteUrl=http://localhost:4444/wd/hub -DpageUrl=http://localhost:8080
